[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$Text,

    [Parameter(Mandatory = $false)]
    [switch]$Approved,

    [Parameter(Mandatory = $false)]
    [string]$Root = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = "Stop"

$RouterScript = Join-Path $PSScriptRoot "Invoke-COOPERTool.ps1"
$ApprovalScript = Join-Path $PSScriptRoot "Resolve-COOPERApproval.ps1"
$WorkbenchScript = Join-Path $PSScriptRoot "Invoke-COOPERWorkbench.ps1"
$ReviewScript = Join-Path $PSScriptRoot "Resolve-COOPERWorkflowReview.ps1"
$MemoryScript = Join-Path $PSScriptRoot "Update-COOPERProjectMemory.ps1"
$SkillsScript = Join-Path $PSScriptRoot "Update-COOPERWorkflowSkills.ps1"
$EvidenceWriterScript = Join-Path $PSScriptRoot "Write-COOPERWorkflowEvidence.ps1"

function Get-COOPERCodexTaskTitle {
    param([Parameter(Mandatory = $true)][string]$RequestText)

    $Clean = [string]$RequestText.Trim()
    foreach ($Pattern in @(
        '^(?i)(create|generate|draft|write|make)\s+(a|an)\s+(codex\s+)?task(\s+to|\s+for|\s+from)?\s+',
        '^(?i)(create|generate|draft|write|make)\s+(a|an)\s+(implementation|development|engineering)\s+task(\s+to|\s+for|\s+from)?\s+',
        '^(?i)(turn|transform|convert)\s+this\s+',
        '^(?i)task\s+to\s+',
        '^(?i)implementation\s+task\s+to\s+',
        '^(?i)development\s+task\s+to\s+',
        '^(?i)engineering\s+task\s+to\s+'
    )) {
        $Clean = [regex]::Replace($Clean, $Pattern, "")
    }

    $Clean = [regex]::Replace($Clean, '[\.\!\?]+$', '').Trim()
    if ([string]::IsNullOrWhiteSpace($Clean) -or $Clean -match '^(?i)this project decision$') {
        $Clean = "Codex Task"
    }

    $TextInfo = [System.Globalization.CultureInfo]::CurrentCulture.TextInfo
    return $TextInfo.ToTitleCase($Clean.ToLowerInvariant())
}

function Get-COOPERCodexTaskSlug {
    param([Parameter(Mandatory = $true)][string]$RequestText)

    $StopWords = @("the", "to", "and", "of", "for", "a", "an", "this", "that", "from", "into", "in", "on", "with", "add", "create", "make", "draft", "write", "generate", "implement", "implementation", "task", "codex")
    $Words = @(
        [regex]::Split(([string]$RequestText).ToLowerInvariant(), '[^a-z0-9]+') |
            Where-Object { -not [string]::IsNullOrWhiteSpace([string]$_) -and $StopWords -notcontains [string]$_ }
    )

    if ($Words.Count -eq 0) {
        return "codex-task"
    }

    $Slug = ($Words | Select-Object -First 6) -join "-"
    if ([string]::IsNullOrWhiteSpace($Slug)) {
        $Slug = "codex-task"
    }
    return $Slug
}

function Get-COOPERCodexTaskPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Root,

        [Parameter(Mandatory = $true)]
        [string]$Title
    )

    $TaskFolder = Join-Path $Root "Codex_Tasks"
    $Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $Slug = Get-COOPERCodexTaskSlug -RequestText $Title
    return [pscustomobject]@{
        folder = $TaskFolder
        path = Join-Path $TaskFolder ("TASK-{0}-{1}.md" -f $Timestamp, $Slug)
    }
}

function New-COOPERCodexTaskMarkdown {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Title,

        [Parameter(Mandatory = $true)]
        [string]$RequestText
    )

    return @(
        "# $Title"
        ""
        "## Objective"
        "Create an implementation-ready Codex task for the supplied project context."
        ""
        "## Background"
        "- Source request: $RequestText"
        "- This task was generated by the governed COOPER task workflow."
        ""
        "## Current State"
        "- The request has not yet been captured as a governed implementation task."
        "- Relevant project context should be translated into bounded work items."
        ""
        "## Required Work"
        "- Analyze the supplied project context."
        "- Turn the request into a concrete implementation task."
        "- Identify the minimal set of files, configuration, or follow-up checks needed."
        "- Keep the task small enough to execute in one governed Codex pass."
        ""
        "## Constraints"
        "- Do not add new frameworks."
        "- Do not redesign the router or workflow architecture."
        "- Do not include secrets, credentials, or private data."
        "- Keep the implementation minimal and reviewable."
        ""
        "## Validation"
        "- Verify the task file exists in the `Codex_Tasks/` folder."
        "- Verify the task includes the required sections."
        "- Verify the task is specific enough to hand to Codex without extra clarification."
        ""
        "## Definition of Done"
        "- The task file is saved in `Codex_Tasks/`."
        "- The content is actionable, bounded, and ready for implementation."
        "- WF-002 review passes."
    ) -join "`r`n"
}

$TaskTitle = Get-COOPERCodexTaskTitle -RequestText $Text
$TaskPathInfo = Get-COOPERCodexTaskPath -Root $Root -Title $TaskTitle
$TaskPath = [string]$TaskPathInfo.path
$MarkdownContent = New-COOPERCodexTaskMarkdown -Title $TaskTitle -RequestText $Text

$RoutedTool = & $RouterScript -ToolId "codex_task_launcher" -Workshop "Open Workshop" -WorkshopMode "Open Workshop" -DryRun
if ([string]$RoutedTool.status -ne "pass") {
    return [pscustomobject]@{
        success = $false
        workflow_id = "WF-002"
        tool_id = "codex_task_launcher"
        task_path = $TaskPath
        routed_tool = $RoutedTool
        approval_decision = $null
        workbench_result = $null
        response_text = [string]$RoutedTool.blocked_reason
        reason = [string]$RoutedTool.blocked_reason
        source_of_truth = "Scripts/Invoke-COOPERCodexTaskGenerator.ps1"
    }
}

$ApprovalDecision = & $ApprovalScript -RoutedToolResult $RoutedTool -Approved:$Approved
if ([bool]$ApprovalDecision.blocked -eq $true -or [bool]$ApprovalDecision.allowed -ne $true -or [bool]$ApprovalDecision.execution_authorized -ne $true) {
    return [pscustomobject]@{
        success = $false
        workflow_id = "WF-002"
        tool_id = "codex_task_launcher"
        task_path = $TaskPath
        routed_tool = $RoutedTool
        approval_decision = $ApprovalDecision
        workbench_result = $null
        response_text = [string]$ApprovalDecision.reason
        reason = [string]$ApprovalDecision.reason
        source_of_truth = "Scripts/Invoke-COOPERCodexTaskGenerator.ps1"
    }
}

$ApprovalDecision | Add-Member -NotePropertyName task_path -NotePropertyValue $TaskPath -Force
$ApprovalDecision | Add-Member -NotePropertyName markdown_content -NotePropertyValue $MarkdownContent -Force

$WorkbenchResult = & $WorkbenchScript -ApprovalDecision $ApprovalDecision

if (-not (Test-Path -LiteralPath $ReviewScript -PathType Leaf)) {
    return [pscustomobject]@{
        success = $false
        workflow_id = "WF-002"
        tool_id = "codex_task_launcher"
        task_path = $TaskPath
        routed_tool = $RoutedTool
        approval_decision = $ApprovalDecision
        workbench_result = $WorkbenchResult
        workflow_review = $null
        response_text = "Workflow review script is unavailable."
        reason = "Workflow review script is unavailable."
        source_of_truth = "Scripts/Invoke-COOPERCodexTaskGenerator.ps1"
    }
}

$WorkflowReview = & $ReviewScript -WorkflowId "WF-002" -WorkflowResult $([pscustomobject]@{
    success = [bool]$WorkbenchResult.success
    workflow_id = "WF-002"
    task_path = $TaskPath
    approval_decision = $ApprovalDecision
    workbench_result = $WorkbenchResult
    response_text = if ($WorkbenchResult.success) { "Created Codex task at $TaskPath." } else { [string]$WorkbenchResult.reason }
    reason = [string]$WorkbenchResult.reason
    output_type = "markdown_file"
    result_artifact_path = $TaskPath
}) -RequestText $Text -ExpectedOutputType "markdown_file" -ExpectedOutputPath $TaskPath -ExpectedContent $Text

if (-not $WorkflowReview -or [string]$WorkflowReview.status -ne "pass") {
    return [pscustomobject]@{
        success = $false
        workflow_id = "WF-002"
        tool_id = "codex_task_launcher"
        task_path = $TaskPath
        routed_tool = $RoutedTool
        approval_decision = $ApprovalDecision
        workbench_result = $WorkbenchResult
        workflow_review = $WorkflowReview
        response_text = if ($WorkflowReview -and $WorkflowReview.PSObject.Properties.Name -contains "issues" -and $WorkflowReview.issues) { [string]($WorkflowReview.issues -join "; ") } else { "Workflow review failed." }
        reason = if ($WorkflowReview -and $WorkflowReview.PSObject.Properties.Name -contains "issues" -and $WorkflowReview.issues) { [string]($WorkflowReview.issues -join "; ") } else { "Workflow review failed." }
        source_of_truth = "Scripts/Invoke-COOPERCodexTaskGenerator.ps1"
    }
}

if (Test-Path -LiteralPath $MemoryScript -PathType Leaf) {
    try {
        $null = & $MemoryScript -WorkflowId "WF-002" -ReviewResult $WorkflowReview -RequestText $Text -OutputPath $TaskPath
    }
    catch {}
}

if (Test-Path -LiteralPath $SkillsScript -PathType Leaf) {
    try {
        $ExampleOutput = [System.IO.Path]::GetFileName($TaskPath)
        $null = & $SkillsScript -WorkflowId "WF-002" -ReviewResult $WorkflowReview -ExampleRequest $Text -ExampleOutput $ExampleOutput -SkillName "Codex Task Generator"
    }
    catch {}
}

if (-not (Test-Path -LiteralPath $EvidenceWriterScript -PathType Leaf)) {
    throw "Workflow evidence writer is unavailable."
}

$ExecutionId = (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssfffZ")
$EvidenceResult = & $EvidenceWriterScript -Root $Root -RecordType "completion" -WorkshopId "open" -WorkflowId "WF-002" -WorkflowName "Codex Task Generator" -ExecutionId $ExecutionId -Status "pass" -CompletionTime ((Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")) -ApprovalId "" -ArtifactPaths @($TaskPath) -ReviewStatus "unknown" -UserAccepted:$false -Notes "WF-002 task generation completed; review pending."

return [pscustomobject]@{
    success = $true
    workflow_id = "WF-002"
    tool_id = "codex_task_launcher"
    task_path = $TaskPath
    evidence_path = [string]$EvidenceResult.path
    routed_tool = $RoutedTool
    approval_decision = $ApprovalDecision
    workbench_result = $WorkbenchResult
    workflow_review = $WorkflowReview
    response_text = "Created Codex task at $TaskPath."
    reason = [string]$WorkbenchResult.reason
    source_of_truth = "Scripts/Invoke-COOPERCodexTaskGenerator.ps1"
}
