$Root = Split-Path $PSScriptRoot -Parent

$Required = @(
    "workers.json",
    "Scripts\PDA_WorkerContract.schema.json",
    "Scripts\PDA_TaskRequest.schema.json",
    "Scripts\PDA_MultiAgentTask.schema.json",
    "Scripts\PDA_TaskOntology.json",
    "Scripts\PDA_TaskOntology.schema.json",
    "Scripts\PDA_TaskOntology.ps1",
    "Scripts\PDA_MemoryTaxonomy.json",
    "Scripts\PDA_MemoryTaxonomy.schema.json",
    "Scripts\PDA_MemoryTaxonomy.ps1",
    "Scripts\PDA_LegacyMemoryRepairAllowlist.json",
    "Scripts\PDA_LifecyclePolicy.json",
    "Scripts\PDA_LifecyclePolicy.schema.json",
    "Scripts\PDA_Lifecycle.ps1",
    "Scripts\PDA_ModelRouting.json",
    "Scripts\PDA_CapabilityRegistry.json",
    "Scripts\PDA_AgentProfileRegistry.json",
    "Scripts\PDA_ProviderRoutingPolicy.json",
    "Scripts\PDA_ToolRegistry.json",
    "Scripts\PDA_ExecutionRequestRegistry.json",
    "Scripts\PDA_ExecutionPlanRegistry.json",
    "Scripts\PDA_Retrieval.ps1",
    "Scripts\PDA_ApprovedEntrypoints.json",
    "Scripts\Validate-PDATaskOntology.ps1",
    "Scripts\Validate-PDAMemoryTaxonomy.ps1",
    "Scripts\Validate-PDALifecyclePolicy.ps1",
    "Scripts\Get-PDATaskType.ps1",
    "Scripts\Resolve-PDATaskWorkers.ps1",
    "Scripts\Get-PDAArtifacts.ps1",
    "Scripts\Get-PDAMemory.ps1",
    "Scripts\Get-PDATaskOntologyEntry.ps1",
    "Scripts\Get-PDAWorkerCapability.ps1",
    "Scripts\Get-PDACapability.ps1",
    "Scripts\Get-PDAAgentProfile.ps1",
    "Scripts\Resolve-PDAAgent.ps1",
    "Scripts\Get-PDAModelRoute.ps1",
    "Scripts\Resolve-PDAExecutionPlan.ps1",
    "Scripts\Resolve-PDATool.ps1",
    "Scripts\PDA_CommandInterpreter.ps1",
    "Scripts\Invoke-PDACommandHandoff.ps1",
    "Scripts\Invoke-PDAChatBridge.ps1",
    "Scripts\Get-PDATaskResult.ps1",
    "Scripts\PDA_PlanOrchestration.ps1",
    "Scripts\PDA_AgentLoop.ps1",
    "Scripts\PDA_AgentToolRegistry.json",
    "Scripts\PDA_ApprovalWorkflow.ps1",
    "Scripts\Get-PDATool.ps1",
    "Scripts\Get-PDAExecutionRequest.ps1",
    "Scripts\New-PDAExecutionRequest.ps1",
    "Scripts\New-PDAApprovalRequest.ps1",
    "Scripts\Get-PDAApprovalRequest.ps1",
    "Scripts\Update-PDAApprovalRequest.ps1",
    "Scripts\Get-PDAApprovalWorkflowStatus.ps1",
    "Scripts\Get-COOPERIdentity.ps1",
    "Scripts\COOPER_Personality.json",
    "Scripts\PDA_Environment.ps1",
    "Scripts\New-PDAPlanInstance.ps1",
    "Scripts\Invoke-PDAPlan.ps1",
    "Scripts\Get-PDAPlanStatus.ps1",
    "Scripts\Get-PDAPlanResults.ps1",
    "Scripts\Test-PDAToolRegistry.ps1",
    "Scripts\Test-PDAExecutionRequest.ps1",
    "Scripts\Test-PDAExecutionFoundation.ps1",
    "Scripts\New-PDAAgentRun.ps1",
    "Scripts\Get-PDAAgentRun.ps1",
    "Scripts\Update-PDAAgentRun.ps1",
    "Scripts\Invoke-PDAAgentLoop.ps1",
    "Scripts\Test-PDAAgentLoop.ps1",
    "Scripts\Test-PDAApprovalWorkflow.ps1",
    "Scripts\Get-PDAFilesystemInventory.ps1",
    "Scripts\Get-PDARepositoryInventory.ps1",
    "Scripts\Get-PDADockerInventory.ps1",
    "Scripts\Get-PDAServiceInventory.ps1",
    "Scripts\Get-PDAToolInventory.ps1",
    "Scripts\Get-PDAEnvironmentSummary.ps1",
    "Scripts\Get-PDAFileOrganizationRecommendation.ps1",
    "Scripts\PDA_DecisionEngine.ps1",
    "Scripts\Test-PDACommanderDecisionEngine.ps1",
    "Scripts\Invoke-PDAWebhookBridge.ps1",
    "Scripts\New-PDAHttpBridgeWorkflow.ps1",
    "Scripts\New-PDAN8nClipboardWorkflow.ps1",
    "Scripts\Start-PDAWebhookServer.ps1",
    "Scripts\Get-PDAMemoryRepairReport.ps1",
    "Scripts\Set-PDAArtifactLifecycle.ps1",
    "Scripts\Set-PDAMemoryLifecycle.ps1",
    "Scripts\Test-PDATaskOntology.ps1",
    "Scripts\Test-PDAMemoryTaxonomy.ps1",
    "Scripts\Test-PDAMemoryWriterEnforcement.ps1",
    "Scripts\Test-PDALegacyMemoryRepair.ps1",
    "Scripts\Test-PDALifecycle.ps1",
    "Scripts\Test-PDAOntologyDispatch.ps1",
    "Scripts\Test-PDAPreDispatchBypass.ps1",
    "Scripts\Test-PDAOntologyGovernance.ps1",
    "Scripts\Test-PDAOntologyGovernanceDrift.ps1",
    "Scripts\Test-PDARepoGovernance.ps1",
    "Scripts\Test-PDARetrieval.ps1",
    "Scripts\Test-PDAModelRouting.ps1",
    "Scripts\Invoke-PDAModel.ps1",
    "Scripts\Test-PDAModelInvocation.ps1",
    "Scripts\Test-PDAModelFallback.ps1",
    "Scripts\Test-PDACommandInterpreter.ps1",
    "Scripts\Test-PDACommandHandoff.ps1",
    "Scripts\Test-PDAChatBridge.ps1",
    "Scripts\Invoke-PDADraftWorker.ps1",
    "Scripts\Test-PDADraftWorker.ps1",
    "Scripts\Invoke-PDAResearchWorker.ps1",
    "Scripts\Test-PDAResearchWorker.ps1",
    "Scripts\Test-PDAReviewWorker.ps1",
    "Scripts\Invoke-PDAFabricPattern.ps1",
    "Scripts\Test-PDAFabricPattern.ps1",
    "Scripts\Test-PDATaskResult.ps1",
    "Scripts\Test-PDALiteLLMProviders.ps1",
    "Scripts\Test-PDALiteLLMEnv.ps1",
    "Scripts\Test-PDAWebhookBridge.ps1",
    "Scripts\Test-PDAHttpBridgeWorkflow.ps1",
    "Scripts\Test-PDAN8nClipboardWorkflow.ps1",
    "Scripts\Test-PDAWebhookServerReachability.ps1",
    "Scripts\Test-PDACapabilityRegistry.ps1",
    "Scripts\Test-PDAAgentProfileRegistry.ps1",
    "Scripts\Test-PDAAgentResolver.ps1",
    "Scripts\Test-PDAOpenWebUIIdentityPersistence.ps1",
    "Scripts\Resolve-PDAProvider.ps1",
    "Scripts\Test-PDAProviderResolver.ps1",
    "Scripts\Test-PDAExecutionPlanResolver.ps1",
    "Documentation\OpenWebUI-Integration.md",
    "Documentation\COOPER-OpenWebUI-Operator-Model.md",
    "Documentation\COOPER-Agent-Routing-Architecture.md",
    "Documentation\COOPER-Identity-and-Personality.md",
    "Documentation\COOPER-Execution-Foundation.md",
    "n8n Workflow\PDA-ChatBridge.json",
    "n8n Workflow\PDA-ChatBridge-HTTP.json",
    "n8n Workflow\PDA-ChatBridge-HTTP-Clipboard.json",
    "Scripts\New-PDATask.ps1",
    "Scripts\Get-PDATaskStatus.ps1",
    "Scripts\Invoke-PDAReporterWorker.ps1",
    "Scripts\Test-PDAReporterWorker.ps1",
    "Scripts\Start-PDAMultiAgentIntakeWatcher.ps1",
    "Scripts\Process-PDACommandStagedTasks.ps1",
    "Scripts\Invoke-PDAResearchWorker.ps1",
    "Scripts\Invoke-PDAExecuteWorker.ps1",
    "Scripts\Test-PDAPlanOrchestration.ps1",
    "Scripts\Test-PDAEnvironmentAwareness.ps1",
    "Documentation\PDA-Agent-Loop-Architecture.md",
    "PDA-Fabric",
    "PDA-Fabric\Research",
    "PDA-Fabric\Reporting",
    "PDA-Fabric\Review",
    "PDA-Fabric\Security",
    "PDA-Tasks\pending",
    "PDA-Tasks\running",
    "PDA-Tasks\completed",
    "PDA-Tasks\failed",
    "PDA-Tasks\results"
)

# Deprecated legacy queue directories are not required for a passing check.
$LegacyOptional = @(
    "Tasks\queued",
    "Tasks\running",
    "Tasks\completed",
    "Tasks\failed",
    "Tasks\results"
)

foreach ($Item in $Required) {
    $Path = Join-Path $Root $Item
    if (Test-Path $Path) {
        Write-Host "[OK] $Item"
    } else {
        Write-Host "[MISSING] $Item"
    }
}

Write-Host ""
Write-Host "Optional legacy queue paths:"
foreach ($Item in $LegacyOptional) {
    $Path = Join-Path $Root $Item
    if (Test-Path $Path) {
        Write-Host "[LEGACY] $Item"
    }
}
